version: '3.8'
services:

  pyclibrary-lint:
    build:
      context: ./
    volumes:
      - ./:/app
    command: python -m pylint ./pyclibrary

  pyclibrary-utest:
    build:
      context: ./
    volumes:
      - ./:/app
    command: python -m pytest tests --cov pyclibrary --cov-report xml -v
    depends_on:
      - pyclibrary-lint