version: '3.8'
services:

  lint:
    build:
      context: ./
    volumes:
      - ./:/app
    command: python -m pylint ./pyclibrary

  utest:
    build:
      context: ./
    volumes:
      - ./:/app
    ports:
      - '5678:5678'
    command: python -m pytest tests --cov pyclibrary --cov-report xml -v
    